---
title: "CogE Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(ggplot2)
library(dplyr)
library(lattice)
library(rstatix)
library(ez)
library(DescTools)
```

```{r}
data <- read_excel("COGDEC.xlsx")
View(data)

```
```{r}

data1 <- subset(data, data$`Over 4800`=="N")
data1
data1$Group <- as.factor(data1$Group)


gm1 <- aggregate(data1$Score, list(data1$Group), FUN=mean)
gm2 <- aggregate(data1$Score, list(data1$Group), FUN=sd)

gm1
gm2
```


```{r}
vis <- ggplot(data, aes(x = Group, y = Score))+
  geom_boxplot()

vis1 <- ggplot(data1, labels = c("c","con","rub"), aes(x = Group, y = Score, colour = Group))+
  geom_boxplot(aes(fill = Group))+
  scale_color_manual(values = c("mediumturquoise", "whitesmoke", "paleturquoise"), labels = c("Cancelation","Control","Rebus"))+
  scale_fill_manual(values = c("blue", "deeppink", "purple"), labels = c("Cancelation","Control","Rebus"))+
  theme_dark()
 
vis2 <- vis1 + labs(title = "Average Amount of Questions Answered Within Each Group")
vis2
```

```{r}
anv1 <- anova_test(data = data1, dv = Score, wid = Participant, within = Group)
anv1
get_anova_table(anv1)



```


```{r}
summary(cc<-aov(Score~as.factor(Group),data= data1))
TukeyHSD(cc,"as.factor(Group)",data=data1)

```

